definitions:
  env_versions: &env_versions
    xcode: 15.4
  triggering:
    push: &push_event
      events:
        - push
  scripts:
    - &runBenchmarkTests
      name: Run benchmark tests
      script: sh benchmark.sh
workflows:
  ios-m2-mac-mini-workflow:
    name: iOS M2 Mac Mini Workflow
    instance_type: mac_mini_m2
    environment:
      <<: *env_versions
    triggering:
      <<: *push_event
    scripts:
      - *runBenchmarkTests
workflows:
  ios-intel:
    name: iOS Mac Pro workflow
    instance_type: mac_pro
    environment:
      xcode: latest
    triggering:
      <<: *push_event
    scripts:
      - *runBenchmarkTests
